### ISSUE TITLE
Hidden title when hover on compoment??

### ISSUE THREAD

**Issue by rashaHm** [mrastiak/vue-notification-bell#23]

**Comment by maryayi** [comment]
@rashaHm Can you explain more? I didn't get your point

**Comment by kerrpeter** [comment]
I'm assuming that like me he doesn't want the default title tag on the SVG image of "bell"
The html render has `<title>bell</title>` added to it, so when you hover on the notification icon the title of "bell" pops up.

Can we have an option to either hide this or better yet to pass in what we want to be displayed

**Comment by maryayi** [comment]
@kerrpeter Yes, that's definitely a bug. thanks for the clarification. I have fixed that and removed the dummy title for now.

**Comment by kerrpeter** [comment]
Fair play for the speedy fix
