### ISSUE TITLE
'notificationBell' ID appears many times

### ISSUE THREAD

**Issue by windu2b** [mrastiak/vue-notification-bell#29]
In the same page, I have several notifications bells, which all of them with the same id "notificationBell". It's confusing and can create some javascript issues.
Instead of that, why don't replace this id by a class, or allow to define the notification bell's ID with a param, like this ?
`<notification-bell :id=[my chosen unique ID] ... />`

**Comment by maryayi** [comment]
@windu2b You are right. I will replace the `id` with `class`. thanks for reporting this
